name: Wirediff CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  QT_VERSION: 5.15.2

jobs:
  build_windows:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        host: windows
        target: desktop
        version: ${{ env.QT_VERSION }}
        arch: win64_msvc2019_64
    - name: Set MSVC command prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Create Makefile
      run: qmake
    - name: Build
      run: |
        nmake
        cd release
        windeployqt qtwirediff.exe --pdb --release --compiler-runtime
        copy C:\Windows\System32\concrt140.dll . 
        copy C:\Windows\System32\vccorlib140.dll .
        copy C:\Windows\System32\msvcp140.dll .
        copy C:\Windows\System32\vcruntime140.dll .
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Wirediff (Windows)
        path: release
